puppies/config/routes.rb
Puppies::Application.routes.draw do
  get 'admin' => 'admin#index'
  
  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'login' => :destroy
  end

  resources :users

  resources :orders

  resources :adoptions

  resources :carts

  get "agency/index"

  resources :puppies

  root :to => "agency#index", :as => 'agency'

end

puppies/app/models/adoption.rb
class Adoption < ActiveRecord::Base
  belongs_to :order
  belongs_to :puppy
  belongs_to :cart

  def total_price
    puppy.fees
  end
end

puppies/app/controllers/adoptions_controller.rb
class AdoptionsController < ApplicationController
  skip_before_filter :authorize
  
  # GET /adoptions
  def index
    @adoptions = Adoption.all

    respond_to do |format|
      format.html # index.html.erb
    end
  end

  # GET /adoptions/1
  def show
    @adoption = Adoption.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
    end
  end

  # GET /adoptions/new
  def new
    @adoption = Adoption.new

    respond_to do |format|
      format.html # new.html.erb
    end
  end

  # GET /adoptions/1/edit
  def edit
    @adoption = Adoption.find(params[:id])
  end

  # POST /adoptions
  def create
    @cart = current_cart
    puppy = Puppy.find(params[:puppy_id])
    @adoption = @cart.add_puppy(puppy.id)

    respond_to do |format|
      if @adoption.save
        format.html { redirect_to(@adoption.cart) }
        format.json { render :json => @adoption }
      else
        format.html { render :action => "new" }
      end
    end
  end

  # PUT /adoptions/1
  def update
    @adoption = Adoption.find(params[:id])

    respond_to do |format|
      if @adoption.update_attributes(params[:adoption])
        format.html { redirect_to(@adoption, :notice => 'Adoption was successfully updated.') }
      else
        format.html { render :action => "edit" }
      end
    end
  end

  # DELETE /adoptions/1
  def destroy
    @adoption = Adoption.find(params[:id])
    @adoption.destroy

    respond_to do |format|
      format.html { redirect_to(adoptions_url) }
    end
  end
end

puppies/app/helpers/adoptions_helper.rb
module AdoptionsHelper
end

puppies/app/views/adoptions/_adoption.html.erb
<tr>
  <td><%= image_tag(adoption.puppy.image_url, :width => '30') %></td>
  <td><h2><%= adoption.puppy.name %>:</h2></td>
  <td><h2><%= adoption.puppy.gender %> - <%= adoption.puppy.breed %></h2></td>
  <td class="item_price"><h2><%= number_to_currency(adoption.total_price) %></h2></td>
</tr>
<tr>
  <td colspan="2"></td>
  <td><h3>Additional Products/Services</h3></td>
</tr>
<tr>
  <td colspan="2"></td>
  <td><%= check_box_tag 'collar'%> Collar & Leash ($19.99)</td>
  <td><div class="collar-amount"></div></td>
</tr>
<tr>
  <td colspan="2"></td>
  <td><%= check_box_tag 'toy'%> Chew Toy ($8.99)</td>
  <td><div class="toy-amount"></div></td>
</tr>
<tr>
  <td colspan="2"></td>
  <td><%= check_box_tag 'carrier'%> Travel Carrier ($39.99)</td>
  <td><div class="carrier-amount"></div></td>
</tr>
<tr>
  <td colspan="2"></td>
  <td><%= check_box_tag 'vet'%> First Vet Visit ($69.99)</td>
  <td><div class="vet-amount"></div></td>
</tr>

puppies/app/views/adoptions/_form.html.erb
<%= form_for(@adoption) do |f| %>
  <% if @adoption.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@adoption.errors.count, "error") %> prohibited this adoption from being saved:</h2>

      <ul>
      <% @adoption.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :puppy_id %><br />
    <%= f.text_field :puppy_id %>
  </div>
  <div class="field">
    <%= f.label :cart_id %><br />
    <%= f.text_field :cart_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

puppies/app/views/adoptions/edit.html.erb
<h1>Editing adoption</h1>

<%= render 'form' %>

<%= link_to 'Show', @adoption %> |
<%= link_to 'Back', adoptions_path %>

puppies/app/views/adoptions/index.html.erb
<h1>Listing adoptions</h1>

<table>
  <tr>
    <th>Puppy</th>
    <th>Cart</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @adoptions.each do |adoption| %>
  <tr>
    <td><%= adoption.puppy_id %></td>
    <td><%= adoption.cart_id %></td>
    <td><%= link_to 'Show', adoption %></td>
    <td><%= link_to 'Edit', edit_adoption_path(adoption) %></td>
    <td><%= link_to 'Destroy', adoption, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Adoption', new_adoption_path %>

puppies/app/views/adoptions/new.html.erb
<h1>New adoption</h1>

<%= render 'form' %>

<%= link_to 'Back', adoptions_path %>

puppies/app/views/adoptions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Puppy:</b>
  <%= @adoption.puppy_id %>
</p>

<p>
  <b>Cart:</b>
  <%= @adoption.cart_id %>
</p>


<%= link_to 'Edit', edit_adoption_path(@adoption) %> |
<%= link_to 'Back', adoptions_path %>