puppies/config/routes.rb
Puppies::Application.routes.draw do
  get 'admin' => 'admin#index'
  
  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'login' => :destroy
  end

  resources :users

  resources :orders

  resources :adoptions

  resources :carts

  get "agency/index"

  resources :puppies

  root :to => "agency#index", :as => 'agency'

end

puppies/app/models/puppy.rb
class Puppy < ActiveRecord::Base
  default_scope :order => 'name'
  has_many :adoptions

  before_destroy :ensure_not_referenced_by_any_adoption
  
  validates :name, :breed, :image_url, :presence => true
  validates :fees, :numericality => {:greater_than => 0.00}
  validates :image_url, :format => {
    :with => %r{\.(gif|jpg|png)}i,
    :message => 'must be a URL for GIF, JPG, or PNG image.'}

  def ensure_not_referenced_by_any_adoption
    if adoptions.count.zero?
      return true
    else
      errors[:base] << "Adoption present"
      return false
    end
  end
end

puppies/app/controllers/puppies_controller.rb
class PuppiesController < ApplicationController
  skip_before_filter :authorize, :only => [:index, :show]
  
  def index
    @puppies = Puppy.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @puppies }
    end
  end

  def show
    @puppy = Puppy.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @puppy }
    end
  end

  def new
    @puppy = Puppy.new

    respond_to do |format|
      format.html # new.html.erb
    end
  end

  def edit
    @puppy = Puppy.find(params[:id])
  end

  def create
    @puppy = Puppy.new(params[:puppy])

    respond_to do |format|
      if @puppy.save
        format.html { redirect_to(@puppy, :notice => 'Puppy was successfully created.') }
      else
        format.html { render :action => "new" }
      end
    end
  end

  def update
    @puppy = Puppy.find(params[:id])

    respond_to do |format|
      if @puppy.update_attributes(params[:puppy])
        format.html { redirect_to(@puppy, :notice => 'Puppy was successfully updated.') }
      else
        format.html { render :action => "edit" }
      end
    end
  end

  def destroy
    @puppy = Puppy.find(params[:id])
    @puppy.destroy

    respond_to do |format|
      format.html { redirect_to(puppies_url) }
    end
  end
end

puppies/app/helpers/puppies_helper.rb
module PuppiesHelper
end

puppies/app/views/puppies/_form.html.erb
<%= form_for(@puppy) do |f| %>
  <% if @puppy.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@puppy.errors.count, "error") %> prohibited this puppy from being saved:</h2>

      <ul>
      <% @puppy.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :breed %><br />
    <%= f.text_field :breed %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :gender %><br />
    <%= f.text_field :gender %>
  </div>
  <div class="field">
    <%= f.label :image_url %><br />
    <%= f.text_field :image_url %>
  </div>
  <div class="field">
    <%= f.label :fees %><br />
    <%= f.text_field :fees %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

puppies/app/views/puppies/edit.html.erb
<h1>Editing puppy</h1>

<%= render 'form' %>

<%= link_to 'Show', @puppy %> |
<%= link_to 'Back', puppies_path %>

puppies/app/views/puppies/index.html.erb
<div id="puppy_list">
  <h1>Listing puppies</h1>

  <table>
  <% @puppies.each do |puppy| -%>
    <tr class="<%= cycle('list_line_odd', 'list_line_even') %>">
      <td>
        <%= image_tag(puppy.image_url, :class => 'list_image') %>
      </td>

      <td class='list_description'>
        <dl>
          <dt><%= puppy.name %></dt>
          <dd><%= truncate(strip_tags(puppy.description), :length => 80) %></dd>
        </dl>
      </td>

      <td class='list_actions'>
        <%= link_to 'Show', puppy %><br />
        <%= link_to 'Edit', edit_puppy_path(puppy) %><br />
        <%= link_to 'Destroy', puppy, :confirm => 'Are you sure?', :method => :delete %>
      </td>
    </tr>
  <% end %>
  </table>
</div>

<br />

<%= link_to 'New Puppy', new_puppy_path %>

puppies/app/views/puppies/new.html.erb
<h1>New puppy</h1>

<%= render 'form' %>

<%= link_to 'Back', puppies_path %>

puppies/app/views/puppies/show.html.erb
<% if notice -%>
  <p id='notice'><%= notice %></p>
<% end %>

<div>
  <%= image_tag(@puppy.image_url) %>
  <h2><%= @puppy.name %></h2>
  <h3><%= @puppy.gender %> <%= @puppy.breed %></h3>
  <%= sanitize @puppy.description %>
  <div class='fees_line'>
    <span class="fees">The fees to adopt me are <%= number_to_currency(@puppy.fees) %></span>
    <%= button_to 'Adopt Me!', adoptions_path(:puppy_id => @puppy), :class => 'rounded_button' %>
  </div>
</div>

<br />
<%= link_to 'Return to List', agency_path %>