puppies/config/routes.rb
Puppies::Application.routes.draw do
  get 'admin' => 'admin#index'
  
  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'login' => :destroy
  end

  resources :users

  resources :orders

  resources :adoptions

  resources :carts

  get "agency/index"

  resources :puppies

  root :to => "agency#index", :as => 'agency'

end

puppies/app/views/layouts/application.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<!--
 ____________________________________________________________
|                                                            |
|    DESIGN : Jeremie Tisseau { http://web-kreation.com }    |
|      DATE : 2007.08.31                                     |
| COPYRIGHT : Free use if this notice is left in place       |
|     EMAIL : webmaster@web-kreation.com                     |
|____________________________________________________________|
-->

<head>
  <title>Sally's Puppy Adoption Agency</title>
  <%= stylesheet_link_tag "application", :media => 'all' %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tag %>
</head>
<body>
    <div id="container">
        <div id="wrapper">
            <div id="sidebar">
                <div id="sb_top">
                   <div class="sb_logo">
                      <a href="index.html" title="Home"><%= image_tag("logo.png", :alt => "Home") %></a>
                    </div>
                    <p>Home of the Happy Puppy</p>
                </div>

                <div class="sb_content">

                  <ul id="navlist">
                    <li><%= link_to "Adopt a Puppy", agency_path %></li>
                    <li><a href="http://www...">Learn</a></li>
                    <li><a href="http://www...">Animal Shelters</a></li>
                    <li><a href="http://www...">Classifieds</a></li>
                    <li><a href="http://www...">Message Boards</a></li>
                    <li><a href="http://www...">Pet News</a></li>

                    <% if session[:user_id] -%>
                      <li><%= link_to "Adoptions", orders_path %></li>
                      <li><%= link_to "Puppies", puppies_path %></li>
                      <li><%= link_to "Users", users_path %></li>
                      <li><%= link_to 'Logout', login_path, :method => :delete %></li>
                    <% end -%>
                  </ul>

               </div> <!-- /sb_content -->
            </div> <!-- /sidebar -->


            <!-- Top -->
            <div id="header">
                   <input name="search" class="search" type="text" value="Search..." />
                   <a href="contact.php" name="Contact"><%= image_tag("contact.jpg", :alt => "Contact") %></a>
            </div>


            <!-- Start main content -->
            <div id="content">
                <div id="intro">
                    <div class="intro_t">
                      <h1><span>Home of the </span>Happy Puppy</h1>
                    </div>
                </div> <!-- /intro -->
                <%= yield %>
            </div> <!-- /content -->
        </div> <!-- /wrapper -->
        <div class="clear">&nbsp;</div> <!-- Important! Fix the problem of height in Firefox -->
    </div> <!-- /Container -->
</body>
</html>